# Generated by Django 3.1.5 on 2021-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(default='english', max_length=200),
            preserve_default=False,
        ),
    ]
